### ISSUE TITLE
Where are the markdown files that generated the demos?

### ISSUE THREAD

**Issue by rlh100** [slideshow-s9/demos#1]
I am having a very hard time with settig up my first markdown.  I think it is because I need to add slideshow specific commands in my markdown file.  But the documentation does not make that very clear.  The source markdown files for the demo examples would be useful

**Comment by rlh100** [comment]
How do I get h1 paragraphs to start the next slide?  Do I need some sort of <div> or some tag before the h1?

**Comment by geraldb** [comment]
Thanks for your interest slide show (S9). Please post your questions to our [wwwmake forum/mailing list](http://groups.google.com/group/wwwmake) so others can help out too. Your questions are welcome. The issue tracker is just used for bugs (not for questions etc.) Cheers.

**Comment by rlh100** [comment]
Lack of source files for test runs seems like a bug to me.
